### ISSUE TITLE
Adding PyTwin to the PyAnsys metapackage - Needs to support Python 3.7

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/pytwin#55]
Hi all!

As per @MaxJPRey request, I tried to add ``pytwin`` to the ``pyansys`` metapackage repository, so that it is distributed as part of our bundle package.

However, we encountered some issues in the process. It seems that ``pytwin`` does not support Python 3.7.  This is a requirement for the metapackage since we are ensuring that all Python versions that are currently maintained keep being supported. This means Python 3.7 to 3.10. In fact, we are in process of supporting Python 3.11 as well - but this may take a while.

Would it be possible to make ``pytwin`` support Python 3.7? I can help you out implementing the needed changes. Thanks in advance!! 😃

**Comment by lboucin** [comment]
Hell @RobPasMue!
Thanks for looking at this. 
I've created [maint/python_3.7](https://github.com/pyansys/pytwin/tree/maint/python_3.7) branch to implement requested change to support python 3.7. I'll keep you posted once it is done.
FYI @chrpetre

**Comment by RobPasMue** [comment]
That's awesome @lboucin! Thanks for looking into it. If you need any help let me know.

By the way, it looks like your ``pytwin-win10`` runner is offline, all your workflows fail to complete because of this reason. Are you aware of this?

**Comment by lboucin** [comment]
Thank you @RobPasMue for pointing that out to me. I've just restarted the `pytwin-win10` runner and workflows are now running fine now. FYI, we've scheduled to remove this Ansys hosted runner sometime during 23R2 dev cycle.

**Comment by RobPasMue** [comment]
Sounds like a great idea! The more we use GitHub's own runners the better - that way we do not need dedicated machines for running our CI/CD pipelines.

**Comment by lboucin** [comment]
Hello @RobPasMue, Fyi, I'm still working on supporting python3.7 on this branch ([maint/python3.7](https://github.com/pyansys/pytwin/tree/maint/python3.7)). I've encountered multiple issues:
- numpy support for python 3.7 (fixed by [PR63](https://github.com/pyansys/pytwin/pull/63))
- importlib.metadata not a python 3.7 standard package, fixed by importing `importlib_metadata` instead (see [here](https://github.com/pyansys/pytwin/blob/maint/python3.7/src/ansys/pytwin/__init__.py#:~:text=try%3A,import%20importlib_metadata)).
- shutil.copytree does not support `dirs_exist_ok` argument in python 3.7 (on going, see [here](https://github.com/pyansys/pytwin/blob/maint/python3.7/src/ansys/pytwin/settings.py#:~:text=try%3A-,shutil.copytree(,),-except%20TypeError%3A)). I am not sure what is the best way to fix this later one. Do you have an idea?

**Comment by RobPasMue** [comment]
Hi @lboucin!

* Yes, indeed, PR #63 should fix the numpy issue. It will resolve the version needed for your Python version.
* ``importlb_metadata`` is needed for Python 3.7 indeed. You could add it to your dependencies (in your pyproject.toml file) as follows:
```toml
[tool.poetry.dependencies]
...
importlib-metadata = {version = "^4.0", python = "<3.8"}
```
* Hmm that last point with ``shutil.copytree`` is interesting... what about ``distutils``? See https://docs.python.org/3/distutils/apiref.html#distutils.dir_util.copy_tree Let me know if that could work for you.

**Comment by lboucin** [comment]
Hello @RobPasMue, [PR66](https://github.com/pyansys/pytwin/pull/66) should solve this issue. Could you please review it? Thanks!

**Comment by lboucin** [comment]
Completed with [PR66](https://github.com/pyansys/pytwin/pull/66)

**Comment by RobPasMue** [comment]
Awesome! I recommend you do a new release with all these changes whenever possible :)
